### ISSUE TITLE
couchdb doesn't start

### ISSUE THREAD

**Issue by indykish** [megamsys/gru#19]
The directory in [line 41](https://github.com/megamsys/gru/blob/master/site/couchdb/script/couchdb.sh#L41) is missing

![screenshot from 2017-05-10 16-27-51](https://cloud.githubusercontent.com/assets/1402479/25895472/a2cf3be6-359d-11e7-9be4-b972390547c7.png)

**Comment by rajesh-rajagopal** [comment]
couchdb is launched successfully...

**Comment by rajesh-rajagopal** [comment]
close this issue..
